from typing import Any

from .utcdatetime import UTCDateTime

class Inventory:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_channel_metadata(
        self, seed_id: str, datetime: UTCDateTime | None = ...
    ) -> dict[str, Any]: ...
    def get_response(
        self, seed_id: str, datetime: UTCDateTime | None = ...
    ) -> Any: ...
    def select(self, *args: Any, **kwargs: Any) -> Inventory: ...
