from collections.abc import Iterable, Iterator, Sequence
from typing import Any, overload

from .trace import Trace
from .utcdatetime import UTCDateTime

class Stream:
    traces: list[Trace]

    def __init__(self, traces: Sequence[Trace] | None = ...) -> None: ...

    # `__iter__` returns an iterator over a *copy* of `traces`, which is what
    # makes `for tr in st: st.remove(tr)` safe and is documented upstream as
    # such. Nothing in the annotation can express that; it is noted because
    # the idiom looks like a bug and is not.
    def __iter__(self) -> Iterator[Trace]: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> Trace: ...
    @overload
    def __getitem__(self, index: slice) -> Stream: ...
    def __add__(self, other: Stream | Trace) -> Stream: ...
    def __iadd__(self, other: Stream | Trace) -> Stream: ...
    def append(self, trace: Trace) -> Stream: ...
    def extend(self, trace_list: Iterable[Trace]) -> Stream: ...
    def remove(self, trace: Trace) -> Stream: ...
    def copy(self) -> Stream: ...
    def sort(
        self, keys: Sequence[str] = ..., reverse: bool = ...
    ) -> Stream: ...
    def select(
        self,
        network: str | None = ...,
        station: str | None = ...,
        location: str | None = ...,
        channel: str | None = ...,
        sampling_rate: float | None = ...,
        npts: int | None = ...,
        component: str | None = ...,
        id: str | None = ...,
        inventory: Any = ...,
    ) -> Stream: ...
    def trim(
        self,
        starttime: UTCDateTime | None = ...,
        endtime: UTCDateTime | None = ...,
        pad: bool = ...,
        keep_empty_traces: bool = ...,
        nearest_sample: bool = ...,
        fill_value: float | None = ...,
    ) -> Stream: ...
    def detrend(self, type: str = ..., **options: Any) -> Stream: ...
    # `*args, **kwargs` upstream — it forwards to `Trace.taper`.
    def taper(self, *args: Any, **kwargs: Any) -> Stream: ...
    def remove_response(self, *args: Any, **kwargs: Any) -> Stream: ...
    def normalize(self, global_max: bool = ...) -> Stream: ...
    def merge(
        self,
        method: int = ...,
        fill_value: float | str | None = ...,
        interpolation_samples: int = ...,
        **kwargs: Any,
    ) -> Stream: ...
    def plot(self, *args: Any, **kwargs: Any) -> Any: ...
