from datetime import datetime
from typing import Any, overload

import numpy as np

class UTCDateTime:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    # Adding or subtracting seconds gives another instant; subtracting two
    # instants gives the seconds between them. Both spellings are used, and
    # `UTCDateTime` defines no `__radd__` — `float + UTCDateTime` raises, which
    # is a bug this package has already been bitten by once (see `cut_c`).
    def __add__(self, other: float) -> UTCDateTime: ...
    @overload
    def __sub__(self, other: UTCDateTime) -> float: ...
    @overload
    def __sub__(self, other: float) -> UTCDateTime: ...
    def __lt__(self, other: UTCDateTime) -> bool: ...
    def __le__(self, other: UTCDateTime) -> bool: ...
    def __gt__(self, other: UTCDateTime) -> bool: ...
    def __ge__(self, other: UTCDateTime) -> bool: ...
    def __float__(self) -> float: ...
    @property
    def timestamp(self) -> float: ...
    @property
    def datetime(self) -> datetime: ...
    #: `numpy.float64` on the running library, not a builtin `float`.
    @property
    def matplotlib_date(self) -> np.float64: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...
    @property
    def hour(self) -> int: ...
    @property
    def minute(self) -> int: ...
    @property
    def second(self) -> int: ...
    @property
    def microsecond(self) -> int: ...
