"""``core.collection``: the binning, the pairing and the band that survives it.

Every function the legacy kept as a private method is reachable directly here,
so the binning and the band search are tested on constructed input rather than
only as a side effect of running the whole pipeline on real waveforms. That was
the practical cost of the old design: a bug in
``SNP.find_optimal_signal_bandwidth`` could only be observed through 28
stations' worth of end-to-end run.

This file used to hold the other half too — the same 28 windows run through
both ``SNP`` and ``SpectrumPair`` and compared. ``spectral`` is deleted, so
those have no subject; the comments where they stood say what replaced each
guarantee. The short version is the golden reference, which was generated by
the legacy path and is still reproduced unregenerated, so the claim outlives
the code that first made it.
"""

from __future__ import annotations

import contextlib
import copy
import dataclasses
import io
import warnings
from pathlib import Path
from typing import Any
from unittest import mock

import numpy as np
import pytest

obspy = pytest.importorskip("obspy")

from specmod.core import Spectrum  # noqa: E402
from specmod.core import noise as noise_module  # noqa: E402
from specmod.core.bandwidth import (  # noqa: E402
    BANDWIDTH_SELECTORS,
    BandwidthSelector,
    FixedBandwidth,
    WidestBandwidth,
    cap_to_nyquist,
    get_bandwidth_selector,
)
from specmod.core.collection import (  # noqa: E402
    BinnedSpectrum,
    SpectrumPair,
    SpectrumSet,
    _clamp_to_floor,
    find_bandwidth,
    log_bin,
    parseval_scale,
)
from specmod.core.noise import (  # noqa: E402
    NOISE_MODELS,
    NoiseModel,
    boost_noise,
    get_noise_model,
    rotate_log_spectrum,
    rotate_noise,
)
from specmod.fitting import (  # noqa: E402
    FitSpectrum,
    fittable_signal,
    selected_band,
)
from specmod.pipeline import pair_from_traces  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "Tutorial" / "Data" / "2019-08-26T07:30:47.0"
INVENTORY = ROOT / "Tutorial" / "MetaData" / "pnr_inventory.xml"

ORIGIN = "2019-08-26T07:49:24.2"
LATITUDE, LONGITUDE, DEPTH_KM = 53.784, -2.967, 2.1


# --------------------------------------------------------------- unit tests


def test_log_bin_clamps_to_the_records_own_range() -> None:
    """The defaults are far wider than any record, and used to waste the count."""
    freq = np.linspace(1.0, 50.0, 500)
    binned = log_bin(freq, np.ones_like(freq), f_min=0.001, f_max=200.0, n_bins=51)

    assert binned.freq.min() >= 1.0
    assert binned.freq.max() <= 50.0
    # Unclamped, most of the 50 bins would fall outside [1, 50] and be dropped.
    assert len(binned) > 40, f"only {len(binned)} bins survived"


def test_log_bin_averages_geometrically() -> None:
    """The bins are spaced on a log scale, so the average is taken on one too.

    ``n_bins=2`` gives a single bin spanning the whole clamped range, so both
    samples land in it — with more bins the clamping to ``[10.0, 10.1]`` splits
    them and each bin holds one sample.
    """
    freq = np.array([10.0, 10.1])
    amp = np.array([1.0, 100.0])
    binned = log_bin(freq, amp, f_min=1.0, f_max=100.0, n_bins=2)

    assert len(binned) == 1
    assert binned.amp[0] == pytest.approx(10.0), "geometric mean of 1 and 100 is 10"
    # An arithmetic mean would be 50.5 — worth stating, since that is the bug
    # this asserts against rather than a hypothetical one.
    assert binned.amp[0] != pytest.approx(50.5)


def test_log_bin_drops_empty_bins_without_warning() -> None:
    freq = np.linspace(10.0, 50.0, 200)
    with warnings.catch_warnings():
        warnings.simplefilter("error", RuntimeWarning)
        binned = log_bin(freq, np.ones_like(freq), f_min=0.001, f_max=200.0, n_bins=99)
    assert np.isfinite(binned.amp).all()


def test_parseval_scale_is_unity_for_equal_lengths() -> None:
    assert parseval_scale(1000, 1000) == pytest.approx(1.0)
    assert parseval_scale(2000, 1000) == pytest.approx(np.sqrt(2.0))


def test_find_bandwidth_tracks_the_true_edges() -> None:
    """The band should sit on the passing region, not lag behind it.

    The old percentile-of-the-sign-integral search returned 9.41 to 28.72 for
    this input — the high edge close, but **the low edge 4.4 Hz late**, which
    matters because the low edge is what constrains ``Omega``. Taking the
    contiguous run directly lands within one bin of the true 5 Hz onset.

    The bound below is half a bin (the grid is 0.495 Hz), which is the best
    any bin-resolution method can do.
    """
    freq = np.linspace(1.0, 50.0, 100)
    snr = np.where((freq > 5.0) & (freq < 30.0), 10.0, 0.5)
    spacing = float(np.diff(freq)[0])

    band = find_bandwidth(freq, snr, threshold=3.0, method="widest")
    assert band is not None
    low, high = band
    assert abs(low - 5.0) <= spacing, f"low edge {low} is more than a bin from 5.0"
    assert abs(high - 30.0) <= spacing, f"high edge {high} is more than a bin from 30"
    # And strictly inside, so it never claims bandwidth that does not pass.
    assert 5.0 < low < high < 30.0


def test_find_bandwidth_returns_none_when_nothing_passes() -> None:
    freq = np.linspace(1.0, 50.0, 100)
    assert find_bandwidth(freq, np.full_like(freq, 0.1), threshold=3.0) is None


def test_find_bandwidth_survives_a_single_noisy_bin() -> None:
    """A one-bin dip must not truncate the band — that is why it integrates."""
    freq = np.linspace(1.0, 50.0, 100)
    snr = np.where((freq > 5.0) & (freq < 30.0), 10.0, 0.5)
    snr[40] = 0.1

    band = find_bandwidth(freq, snr, threshold=3.0, method="widest")
    assert band is not None
    assert band[1] > 25.0, band


def test_binned_spectrum_rejects_mismatched_shapes() -> None:
    with pytest.raises(ValueError, match="must match"):
        BinnedSpectrum(freq=np.arange(5.0), amp=np.arange(4.0))


def test_the_set_behaves_like_a_mapping() -> None:
    pair = object()
    s = SpectrumSet(pairs={"A": pair, "B": pair}, event="e")  # type: ignore[dict-item]
    assert len(s) == 2
    assert s["A"] is pair
    assert sorted(s) == ["A", "B"]
    assert s.ids() == ["A", "B"]


# The legacy-comparison scaffolding lived here: `_windows`, `_legacy`,
# `_as_core`, and the two tests that ran `SNP` alongside `SpectrumPair` on the
# same 28 windows. `spectral` is deleted, so they have no subject.
#
# What replaced each guarantee:
#
# * `test_log_bin_reproduces_the_legacy_binning` -> the golden reference. It
#   was generated by the legacy path and is reproduced by `specmod.pipeline`
#   *without being regenerated*, to 1e-15. That is the same claim made against
#   a committed artefact rather than against live legacy code, which is what
#   lets it outlive the code.
# * `test_the_pair_reproduces_the_legacy_snr_and_band` -> the same, plus the
#   unit tests above, which reach the band search and the binning directly
#   rather than as a side effect of a full run on real waveforms.
#

# ------------------------------------------------------------ failure paths


def test_find_bandwidth_rejects_a_run_shorter_than_min_width() -> None:
    """A band is a run of bins, and two bins is not enough to fit anything.

    The legacy returned a band here regardless, flagging it separately;
    returning None is the point of the new contract. A run exactly at
    ``min_width`` is accepted, so the boundary is checked from both sides.
    """
    freq = np.linspace(1.0, 50.0, 100)

    widest = WidestBandwidth()

    too_short = np.full_like(freq, 0.5)
    too_short[:2] = 10.0
    assert widest.select(freq, too_short, 3.0) is None

    just_enough = np.full_like(freq, 0.5)
    just_enough[:3] = 10.0
    assert widest.select(freq, just_enough, 3.0) is not None


def test_find_bandwidth_rejects_a_band_narrower_than_min_width() -> None:
    freq = np.linspace(1.0, 50.0, 100)
    snr = np.where((freq > 20.0) & (freq < 21.0), 10.0, 0.5)

    assert WidestBandwidth(min_width=20).select(freq, snr, 3.0) is None


def test_boost_noise_rejects_mismatched_shapes() -> None:
    """Three arrays have to agree, and a silent broadcast would be worse."""
    with pytest.raises(ValueError, match="must all match"):
        boost_noise(np.arange(5.0), np.arange(5.0), np.arange(4.0))


def test_a_pair_without_a_band_does_not_pass() -> None:
    """Pure noise resolves no band, so the pair reports failure rather than
    a band that happens to be the whole axis."""
    rng = np.random.default_rng(0)
    freq = np.linspace(1.0, 50.0, 400)
    flat = np.abs(rng.normal(1e-6, 1e-7, freq.size))

    pair = SpectrumPair.compare(
        _spectrum(freq, flat),
        _spectrum(freq, flat),
        threshold=3.0,
        rotate_noise=False,
    )
    assert pair.band is None
    assert not pair.passes


def test_the_floor_can_reject_a_band_entirely() -> None:
    """A floor above the band's high edge leaves nothing measurable.

    Narrowing to ``(floor, high)`` would be wrong when ``floor >= high`` —
    there is no interval left, and returning one would be inventing a result.
    """
    assert _clamp_to_floor((1.0, 5.0), floor=0.5) == (1.0, 5.0)
    assert _clamp_to_floor((1.0, 5.0), floor=2.0) == (2.0, 5.0)
    assert _clamp_to_floor((1.0, 5.0), floor=9.0) is None


def test_passing_filters_out_the_failures() -> None:
    good = SpectrumPair(
        signal=_spectrum(np.array([1.0, 2.0]), np.array([1.0, 1.0])),
        noise=_spectrum(np.array([1.0, 2.0]), np.array([1.0, 1.0])),
        binned_signal=BinnedSpectrum(np.array([1.5]), np.array([1.0])),
        binned_noise=BinnedSpectrum(np.array([1.5]), np.array([1.0])),
        snr=np.array([1.0]),
        resolution_floor=1.0,
        band=(1.0, 2.0),
    )
    bad = dataclasses.replace(good, band=None)

    every = SpectrumSet(pairs={"good": good, "bad": bad}, event="e")
    assert len(every) == 2
    assert every.passing().ids() == ["good"]
    assert every.passing().event == "e"


def _spectrum(freq: np.ndarray, amp: np.ndarray) -> Spectrum:
    return Spectrum(
        freq=freq,
        amp=amp,
        motion="velocity",
        kind="magnitude",
        duration=float(freq.size),
        sampling_rate=100.0,
    )


# ------------------------------------------------------------- noise models


def test_the_registry_resolves_the_default() -> None:
    model = get_noise_model("boost")
    assert model.name == "boost"
    assert isinstance(model, NoiseModel)


def test_an_unknown_noise_model_names_the_available_ones() -> None:
    with pytest.raises(ValueError, match="Unknown noise model"):
        get_noise_model("rotation")


def test_the_legacy_rotate_method_resolves() -> None:
    """`ROT_METHOD = 1`, which used to raise `NotImplementedError` from `SNP`."""
    assert get_noise_model("rotate").name == "rotate"
    assert set(NOISE_MODELS) == {"boost", "rotate", "none"}


def test_every_registered_model_satisfies_the_protocol() -> None:
    """The point of the registry: a new method needs no change anywhere else.

    Each is exercised on the same input, so a model returning the wrong shape
    or a non-positive factor fails here rather than deep in a band search.
    """
    freq = np.linspace(1.0, 50.0, 60)
    signal = 1e-6 * np.exp(-freq / 20.0)
    noise = signal * 0.05

    for name in NOISE_MODELS:
        model = get_noise_model(name)
        assert isinstance(model, NoiseModel), name
        assert model.name == name
        factor = model.factor(freq, noise, signal)
        assert factor.shape == noise.shape, name
        assert np.isfinite(factor).all(), name
        assert (factor > 0).all(), name
        # A noise model may raise the noise; none of them may lower it.
        assert (factor >= 1.0 - 1e-12).all(), f"{name} lowered the noise"


def test_the_null_model_is_the_identity() -> None:
    """`none` exists so a run can show what the correction is doing."""
    freq = np.linspace(1.0, 50.0, 40)
    noise = np.full_like(freq, 1e-8)
    factor = get_noise_model("none").factor(freq, noise, noise * 20)
    assert factor == pytest.approx(np.ones_like(noise))


def test_boost_lifts_the_noise_to_touch_the_signal() -> None:
    """The defining property, stated as a test rather than left in a docstring.

    The lifted noise should reach the signal somewhere and, in the half being
    lifted, not overshoot it — that is what "until it touches" means.
    """
    rng = np.random.default_rng(5)
    freq = np.sort(rng.uniform(0.5, 50.0, 60))
    signal = 10 ** rng.normal(-6, 1, 60)
    noise = signal * 10 ** rng.normal(-1.5, 0.3, 60)

    lifted = noise * get_noise_model("boost").factor(freq, noise, signal)
    assert np.max(lifted / signal) == pytest.approx(1.0, rel=1e-9)


class TestRotateNoise:
    """The legacy ``ROT_METHOD = 1``, ported.

    It was commented out on ``master`` and `SNP` raised rather than running it,
    so there is no published number to preserve — which is what licensed
    solving for the angle instead of stepping to it, and taking the low/high
    split from the signal rather than the noise. See `core.noise`.
    """

    @staticmethod
    def _case(seed: int = 5, n: int = 60) -> tuple[Any, Any, Any]:
        rng = np.random.default_rng(seed)
        freq = np.logspace(-1.0, 1.7, n)
        signal = 1e-6 * freq ** rng.uniform(-2.5, -0.5) * 10 ** rng.normal(0, 0.2, n)
        noise = signal * 10 ** rng.normal(-1.3, 0.2, n)
        return freq, noise, signal

    def test_it_lifts_the_noise_to_touch_the_signal(self) -> None:
        """Same defining property as boost, reached by a different route."""
        freq, noise, signal = self._case()
        lifted = noise * get_noise_model("rotate").factor(freq, noise, signal)
        assert np.max(lifted / signal) == pytest.approx(1.0, rel=1e-9)

    def test_a_rotation_of_zero_is_the_identity(self) -> None:
        freq, noise, _ = self._case()
        rotated = rotate_log_spectrum(np.log10(freq), np.log10(noise), 0.0)
        assert rotated == pytest.approx(np.log10(noise))

    def test_noise_already_at_the_signal_is_left_alone(self) -> None:
        freq, _, signal = self._case()
        factor = get_noise_model("rotate").factor(freq, signal.copy(), signal)
        assert factor == pytest.approx(np.ones_like(factor))

    def test_the_angle_is_continuous_in_the_input(self) -> None:
        """The reason it is bisected rather than stepped.

        The legacy loop advanced by a fixed ``inc`` and stopped at the first
        trial past the touching point, so its answer was a step function of its
        input and two machines differing in the last bit could land either
        side. Perturbing the signal by one part in 1e-12 must move the factor
        by about that much, not by a step.
        """
        freq, noise, signal = self._case()
        model = get_noise_model("rotate")
        base = model.factor(freq, noise, signal)
        nudged = model.factor(freq, noise, signal * (1.0 + 1e-12))
        assert np.max(np.abs(nudged / base - 1.0)) < 1e-8

    def test_the_bracket_resolution_does_not_change_the_answer(self) -> None:
        """What "continuous" buys: the coarse grid only brackets the root.

        Halving the number of bracketing steps changes which interval the root
        is found in, and must not change the root. If it did, the grid would be
        part of the answer — which is exactly what was wrong with stepping.
        """
        freq, noise, signal = self._case()
        base = rotate_noise(freq, noise, signal)
        with mock.patch.object(noise_module, "_BRACKET_STEPS", 37):
            coarse = rotate_noise(freq, noise, signal)
        assert coarse == pytest.approx(base, rel=1e-9)

    def test_it_reaches_the_signal_even_from_thirty_decades_down(self) -> None:
        """The legacy "Didn't ever meet." fallback is very hard to reach.

        Written expecting the opposite, and corrected by the measurement. The
        anchor term ``log_amp[0] * theta`` grows without bound as the angle
        does, so a backward rotation can raise the noise arbitrarily far: even
        thirty decades below the signal it still touches, exactly, well inside
        a quarter turn. The fallback survives for the genuinely degenerate case
        below, not as a routine outcome.
        """
        freq = np.logspace(-1.0, 1.7, 40)
        signal = np.full_like(freq, 1.0)
        noise = np.full_like(freq, 1e-30)
        lifted = noise * rotate_noise(freq, noise, signal)
        assert np.max(lifted / signal) == pytest.approx(1.0, rel=1e-9)

    def test_an_empty_half_contributes_no_rotation(self) -> None:
        """The degenerate case: a half with no bins in it cannot touch anything."""
        freq = np.logspace(-1.0, 1.7, 20)
        log_freq, log_amp = np.log10(freq), np.log10(np.full_like(freq, 1e-9))
        angle = noise_module._touching_angle(
            log_freq,
            log_amp,
            np.zeros_like(freq),
            np.zeros(20, dtype=bool),
            backwards=False,
        )
        assert angle == 0.0

    def test_it_disagrees_with_boost_which_is_why_both_are_kept(self) -> None:
        """Two different claims about the noise give two different bands.

        If these agreed there would be no reason to offer the choice. Asserted
        so that a change collapsing one into the other is visible.
        """
        freq, noise, signal = self._case()
        boost = get_noise_model("boost").factor(freq, noise, signal)
        rotate = get_noise_model("rotate").factor(freq, noise, signal)
        assert np.max(np.abs(rotate / boost - 1.0)) > 0.1

    def test_the_shapes_must_match(self) -> None:
        with pytest.raises(ValueError, match="must all match"):
            rotate_noise(np.ones(5), np.ones(4), np.ones(5))


def test_boost_is_continuous_where_the_noise_crosses_the_signal() -> None:
    """The fourth discontinuity, and the subtlest one.

    A bin that already reaches the signal needs no lift. Expressing that as a
    guard — ``if np.any(noise >= signal): return unchanged`` — makes the
    function jump as a bin crosses: measured at **17.5%** in the median boost
    factor. Expressing it as ``max(0, min(needed))`` gives the same answer,
    because a bin above the signal requires a negative exponent to reach it,
    but passes through zero smoothly.

    It survived the first three fixes and was what still made four CWT
    stations disagree between machines. This sweeps a bin across the boundary
    and asserts the response has no step in it.
    """
    freq = np.linspace(1.0, 40.0, 40)
    signal = np.full_like(freq, 1e-6)

    factors = []
    for a in np.linspace(0.99, 1.01, 501):
        noise = signal * 0.2
        noise[5] = signal[5] * a
        factors.append(float(np.median(boost_noise(freq, noise, signal))))

    steps = np.abs(np.diff(factors))
    # Any residual step must be far below the 17.5% the guarded version showed.
    assert steps.max() < 1e-3, f"largest step {steps.max():.3e} looks like a jump"


# --------------------------------------------------------- bandwidth selectors


#: What each registered selector needs to be built. Only ``fixed`` takes
#: anything: the band is the whole of it, so there is no default to fall back
#: on. The band chosen here sits inside the passing run the protocol test uses,
#: so every selector is judged against the same expectation.
_SELECTOR_KWARGS: dict[str, dict[str, Any]] = {"fixed": {"low": 6.0, "high": 29.0}}

#: The selectors that read the band off the signal-to-noise ratio. ``fixed``
#: is not one of them by design, so invariants about how the ratio is *used*
#: cannot be stated over it.
_AUTOMATIC = sorted(set(BANDWIDTH_SELECTORS) - {"fixed"})


def test_every_registered_selector_satisfies_the_protocol() -> None:
    freq = np.linspace(1.0, 50.0, 100)
    snr = np.where((freq > 5.0) & (freq < 30.0), 10.0, 0.5)

    for name in BANDWIDTH_SELECTORS:
        selector = get_bandwidth_selector(name, **_SELECTOR_KWARGS.get(name, {}))
        assert isinstance(selector, BandwidthSelector), name
        assert selector.name == name
        band = selector.select(freq, snr, 3.0)
        assert band is not None, name
        low, high = band
        assert 5.0 <= low < high <= 30.0, f"{name} strayed outside the passing run"


def test_an_unknown_selector_names_the_available_ones() -> None:
    with pytest.raises(ValueError, match="Unknown bandwidth selector"):
        get_bandwidth_selector("percentile")


def test_every_automatic_selector_declines_rather_than_guessing() -> None:
    """Stated over the automatic selectors only.

    ``fixed`` returns its band against any ratio, including this one — that is
    what it is for, and ``TestFixedBandwidth`` pins it. Including it here would
    either fail or force the invariant to be weakened for every selector.
    """
    freq = np.linspace(1.0, 50.0, 100)
    nothing_passes = np.full_like(freq, 0.1)
    for name in _AUTOMATIC:
        assert get_bandwidth_selector(name).select(freq, nothing_passes, 3.0) is None, (
            name
        )


def test_peak_does_not_run_past_a_failure_immediately_above_it() -> None:
    """Regression for a wrap in the legacy ``BW_METHOD = 2``.

    That version found the bin before the first failure above the peak with
    ``np.where(...)[0] - 1``. When the failure is the bin *immediately* above
    the peak that index is 0, so ``0 - 1`` wrapped to -1 and selected the
    highest frequency in the record — claiming bandwidth all the way to
    Nyquist when the ratio had in fact failed at once.

    Demonstrated: on the input below the legacy returned a high edge of 50 Hz
    against a true 21.6. It does not trigger on the 28 PNR windows, where the
    ported selector agrees with the legacy on all 140 window-estimator pairs,
    but it would badly inflate bandwidth on a spectrum with an isolated peak.
    """
    freq = np.linspace(1.0, 50.0, 20)
    snr = np.full(20, 0.5)
    snr[7], snr[8] = 5.0, 10.0

    band = get_bandwidth_selector("peak").select(freq, snr, 3.0)
    assert band is not None
    assert band[1] < 25.0, f"high edge {band[1]} ran past the failure above the peak"
    assert band[1] == pytest.approx(freq[8])


# `test_spectra_presents_the_same_interface_as_spectrum_set` and
# `test_the_legacy_container_behaves_like_a_mapping` lived here. They asserted
# that `Spectra` and `SpectrumSet` were usable the same way, which is what let
# callers migrate before the container underneath them was swapped. Everything
# has now been swapped, so there is one container and nothing to hold it
# against; `test_the_set_behaves_like_a_mapping` covers what is left.
#

# ----------------------------------------------- the fitter accepts both


def test_the_fitter_takes_what_it_needs_not_a_named_class() -> None:
    """The coupling that kept `Spectra` holding `SNP`.

    `FitSpectrum` used to require `isinstance(signal, spectral.Signal)`, so
    nothing could be fitted unless it *was* the legacy class — which is why the
    container could not be swapped. It now checks for the attributes it reads,
    and says which are missing rather than failing later from inside a band
    selection.
    """
    bare = Spectrum(
        freq=np.array([1.0, 2.0]),
        amp=np.array([1.0, 1.0]),
        motion="velocity",
        kind="magnitude",
        duration=2.0,
        sampling_rate=100.0,
    )
    with pytest.raises(ValueError, match="missing id, bfreq, bamp"):
        FitSpectrum(bare)


def test_selected_band_distinguishes_no_band_from_an_empty_one() -> None:
    """``None`` rather than an empty array.

    The legacy spelling was an empty ``ubfreqs``, which reads equally well as
    "no band survived" and as "a band from nowhere to nowhere". Those are
    different claims, and a fitter acting on the second would fit nothing and
    report success.
    """

    class Selected:
        band = (2.0, 20.0)

    class Rejected:
        band = None

    assert selected_band(Selected()) == (2.0, 20.0)
    assert selected_band(Rejected()) is None
    assert selected_band(object()) is None


def test_fittable_signal_skips_what_the_gate_rejected() -> None:
    class Rejected:
        passes = False
        signal = "unused"

    class Accepted:
        passes = True
        signal = "the spectrum"

    assert fittable_signal(Rejected()) is None
    assert fittable_signal(Accepted()) == "the spectrum"


def test_a_spectrum_pair_can_be_fitted(pnr_windows) -> None:
    """`SpectrumPair` keeps the unbinned spectrum and its binned form apart,
    which is right for the comparison and wrong for a fitter, so
    `for_fitting()` presents them side by side. This runs a real pair through
    `FitSpectrum` and checks it fits over the band the pair selected.
    """
    signal_stream, noise_stream = pnr_windows()
    pair = pair_from_traces(signal_stream[0], noise_stream[0])
    view = pair.for_fitting(id=signal_stream[0].id)

    with contextlib.redirect_stdout(io.StringIO()):
        fit = FitSpectrum(view, llpsp=-7.0, fc=4.0, ts=0.02)
        fit.fit_mod(method="powell")

    assert fit.result.success
    assert fit.describe_model() == "brune+constant_q in velocity"
    # Fitted over the band the pair chose, not the whole axis.
    assert pair.band is not None
    assert fit.mod_freq.min() >= pair.band[0]
    assert fit.mod_freq.max() <= pair.band[1]
    assert fit.mod_freq.size < view.freq.size


def test_the_view_hands_out_metadata_the_fitter_can_copy(pnr_windows) -> None:
    """`core.Spectrum.meta` is a mappingproxy, which `deepcopy` cannot pickle.

    The fitter deepcopies metadata so a fit cannot write back into the spectrum
    it came from. The proxy is right for an immutable spectrum, so the view
    converts — which is the adapter earning its keep rather than either side
    bending.
    """
    signal_stream, noise_stream = pnr_windows()
    meta = pair_from_traces(signal_stream[0], noise_stream[0]).for_fitting().meta
    assert isinstance(meta, dict)
    assert copy.deepcopy(meta) == meta


# ------------------------------------------------- the migration path off SNP
#
# `Spectra.as_spectrum_set()` was the bridge, and the three tests here checked
# that it handed over the very same `SpectrumPair` objects rather than copies.
# There is no longer anything to bridge from: `specmod.pipeline` builds a
# `SpectrumSet` from waveforms directly, and `tests/test_pipeline.py` covers
# that path including fitting a `SpectrumSet` end to end.


# ------------------------------------------------- imposing and capping bands


def _passing_pair(sampling_rate: float = 100.0) -> SpectrumPair:
    """A pair whose ratio passes everywhere, so the band runs to the top.

    Which is the situation the cap exists for: the walk has nothing to stop it
    but the end of the array.
    """
    freq = np.linspace(1.0, sampling_rate / 2, 400)
    signal = _spectrum(freq, np.full(freq.size, 1e-4))
    noise = _spectrum(freq, np.full(freq.size, 1e-6))
    object.__setattr__(signal, "sampling_rate", sampling_rate)
    object.__setattr__(noise, "sampling_rate", sampling_rate)
    return SpectrumPair.compare(signal, noise, threshold=3.0, rotate_noise=False)


class TestFixedBandwidth:
    def test_it_returns_the_band_it_was_given(self) -> None:
        freq = np.linspace(1.0, 50.0, 200)
        snr = np.ones(freq.size)  # fails the threshold everywhere
        assert FixedBandwidth(5.0, 20.0).select(freq, snr, 3.0) == (5.0, 20.0)

    def test_it_ignores_the_ratio_entirely(self) -> None:
        """The distinguishing property: `peak` and `widest` both return None
        for a ratio this bad, and `fixed` does not consult it at all."""
        freq = np.linspace(1.0, 50.0, 200)
        dead = np.zeros(freq.size)
        assert find_bandwidth(freq, dead, 3.0, method="peak") is None
        assert find_bandwidth(freq, dead, 3.0, method="widest") is None
        assert find_bandwidth(freq, dead, 3.0, method=FixedBandwidth(5.0, 20.0)) == (
            5.0,
            20.0,
        )

    def test_it_is_intersected_with_the_frequencies_present(self) -> None:
        freq = np.linspace(2.0, 30.0, 200)
        got = FixedBandwidth(0.1, 500.0).select(freq, np.ones(freq.size), 3.0)
        assert got == (2.0, 30.0)

    def test_a_band_outside_the_record_is_no_band(self) -> None:
        freq = np.linspace(2.0, 30.0, 200)
        assert (
            FixedBandwidth(100.0, 200.0).select(freq, np.ones(freq.size), 3.0) is None
        )

    def test_an_inverted_band_is_rejected_at_construction(self) -> None:
        with pytest.raises(ValueError, match="needs low < high"):
            FixedBandwidth(20.0, 5.0)

    def test_it_is_in_the_registry_and_needs_a_band(self) -> None:
        assert "fixed" in BANDWIDTH_SELECTORS
        assert isinstance(
            get_bandwidth_selector("fixed", low=1.0, high=9.0), BandwidthSelector
        )
        # The common mistake: `bandwidth_method = "fixed"` with nothing beside
        # it. The message has to name the setting, not the dataclass.
        with pytest.raises(ValueError, match="needs a band"):
            get_bandwidth_selector("fixed")

    def test_compare_records_that_the_band_was_imposed(self) -> None:
        pair = _passing_pair()
        chosen = SpectrumPair.compare(
            pair.signal,
            pair.noise,
            threshold=3.0,
            rotate_noise=False,
            bandwidth=FixedBandwidth(5.0, 20.0),
        )
        assert chosen.meta["band_imposed"] == "fixed"
        # An automatic band is not marked, or the flag would say nothing.
        assert "band_imposed" not in pair.meta


class TestNyquistCap:
    def test_it_trims_only_the_high_edge(self) -> None:
        assert cap_to_nyquist((1.0, 48.0), 100.0, 0.8) == (1.0, 40.0)

    def test_a_band_already_inside_the_ceiling_is_untouched(self) -> None:
        assert cap_to_nyquist((1.0, 20.0), 100.0, 0.8) == (1.0, 20.0)

    def test_a_band_entirely_above_the_ceiling_is_no_band(self) -> None:
        """Not a narrower measurement — no measurement. Same answer the
        selectors give when nothing survives."""
        assert cap_to_nyquist((45.0, 48.0), 100.0, 0.8) is None

    def test_the_fraction_is_validated(self) -> None:
        with pytest.raises(ValueError, match="must be in"):
            cap_to_nyquist((1.0, 10.0), 100.0, 1.5)

    def test_it_scales_with_the_sampling_rate(self) -> None:
        """The reason it is a fraction and not a frequency: one setting has to
        mean the same thing on a 100 Hz and a 200 Hz station."""
        assert cap_to_nyquist((1.0, 99.0), 100.0, 0.8) == (1.0, 40.0)
        assert cap_to_nyquist((1.0, 99.0), 200.0, 0.8) == (1.0, 80.0)

    def test_compare_applies_it(self) -> None:
        uncapped = _passing_pair()
        assert uncapped.band is not None
        capped = SpectrumPair.compare(
            uncapped.signal,
            uncapped.noise,
            threshold=3.0,
            rotate_noise=False,
            max_nyquist_fraction=0.5,
        )
        assert capped.band is not None
        assert capped.band[1] <= 25.0
        assert capped.band[1] < uncapped.band[1]
        assert capped.band[0] == uncapped.band[0]

    def test_it_constrains_a_fixed_band_too(self) -> None:
        """The cap is a statement about the recording, not about how the band
        was chosen, so it has to reach the one strategy that ignores the data."""
        pair = _passing_pair()
        capped = SpectrumPair.compare(
            pair.signal,
            pair.noise,
            threshold=3.0,
            rotate_noise=False,
            bandwidth=FixedBandwidth(1.0, 49.0),
            max_nyquist_fraction=0.5,
        )
        assert capped.band is not None
        assert capped.band[1] <= 25.0


class TestWithBand:
    def test_it_returns_a_new_pair_and_leaves_the_original(self) -> None:
        pair = _passing_pair()
        corrected = pair.with_band((2.0, 10.0))
        assert corrected.band == (2.0, 10.0)
        assert pair.band != (2.0, 10.0)
        assert corrected is not pair

    def test_the_comparison_itself_is_carried_over(self) -> None:
        """Only the reading of the ratio is in question, not the ratio."""
        pair = _passing_pair()
        corrected = pair.with_band((2.0, 10.0))
        assert corrected.snr is pair.snr
        assert corrected.signal is pair.signal
        assert corrected.resolution_floor == pair.resolution_floor

    def test_it_is_marked_as_imposed(self) -> None:
        assert _passing_pair().with_band((2.0, 10.0)).meta["band_imposed"] == "manual"

    def test_it_is_intersected_with_the_frequencies_present(self) -> None:
        pair = _passing_pair()
        widest = pair.with_band((1e-6, 1e6))
        assert widest.band is not None
        assert widest.band[0] >= float(pair.binned_signal.freq.min())
        assert widest.band[1] <= float(pair.binned_signal.freq.max())

    def test_a_band_missing_the_record_is_an_error(self) -> None:
        with pytest.raises(ValueError, match="does not overlap"):
            _passing_pair().with_band((500.0, 900.0))

    def test_an_inverted_band_is_an_error(self) -> None:
        with pytest.raises(ValueError, match="needs low < high"):
            _passing_pair().with_band((10.0, 2.0))

    def test_none_rejects_a_pair_the_selector_accepted(self) -> None:
        pair = _passing_pair()
        assert pair.passes
        assert not pair.with_band(None).passes


def test_a_pair_built_with_a_strategy_object_can_still_be_saved() -> None:
    """`compare` accepts a name or an object, and records what it was given so
    `to_motion` can replay it. An object does not survive `json.dumps`, so
    passing one used to make the pair unsaveable — `io.save` raised from inside
    its metadata dump, naming the dataclass rather than the argument.
    """
    import json  # noqa: PLC0415

    pair = _passing_pair()
    for strategy in (FixedBandwidth(2.0, 20.0), "peak"):
        built = SpectrumPair.compare(
            pair.signal,
            pair.noise,
            threshold=3.0,
            rotate_noise=False,
            bandwidth=strategy,
        )
        json.dumps(dict(built.meta))  # would raise on a bare dataclass


def test_a_recorded_strategy_rebuilds_on_replay() -> None:
    """Recording the name and its fields, rather than the object, is what
    makes `to_motion` survive a save and reload rather than only working in
    memory."""
    pair = _passing_pair()
    built = SpectrumPair.compare(
        pair.signal,
        pair.noise,
        threshold=3.0,
        rotate_noise=False,
        bandwidth=FixedBandwidth(2.0, 20.0),
    )
    recorded = built.meta[SpectrumPair.SETTINGS_KEY]["bandwidth"]
    assert recorded == {"name": "fixed", "low": 2.0, "high": 20.0}
    assert built.to_motion("displacement").band is not None
