"""The measured tables in ``docs/`` must match what the code actually does.

Documentation that quotes numbers goes stale silently, and this project's docs
quote a lot of them — position bias, leakage suppression, agreement with
Prieto's package. Every one of those tables is generated by
``tools/measure_docs.py`` and injected between markers, so a change to an
estimator that moves a published number fails here instead of leaving the
prose quietly wrong.

Only the synthetic measurements are checked. The field ones read
``tutorial/data/events/`` and are slow; regenerate those by hand with
``python tools/measure_docs.py --write --field``.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parent.parent


def _load_measure_docs() -> ModuleType:
    """Import ``tools/measure_docs.py``, which is a script rather than a
    package member and so is not importable by name."""
    path = ROOT / "tools" / "measure_docs.py"
    spec = importlib.util.spec_from_file_location("measure_docs", path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["measure_docs"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def measure() -> ModuleType:
    return _load_measure_docs()


def test_every_marker_in_the_docs_has_a_measurement(measure: ModuleType) -> None:
    """A marker naming a measurement that no longer exists would be skipped
    silently, leaving its table frozen at whatever it last said."""
    known = set(measure.SYNTHETIC) | set(measure.FIELD)
    for path in measure.DOCS:
        if not path.exists():
            continue
        for match in measure.MARKER.finditer(path.read_text()):
            name = match.group("name")
            assert name in known, (
                f"{path.relative_to(ROOT)} refers to measurement {name!r}, which "
                f"is not defined in tools/measure_docs.py"
            )


def test_synthetic_tables_match_the_code(measure: ModuleType) -> None:
    """The check that actually bites: regenerate and compare."""
    rendered = measure.render(measure.SYNTHETIC)
    stale: list[str] = []
    for path in measure.DOCS:
        if path.exists():
            _, found = measure.apply_to(path, rendered)
            stale += found
    assert not stale, (
        "documented measurements no longer match the code: "
        + ", ".join(stale)
        + "\nrun: python tools/measure_docs.py --write"
    )


def test_measurements_are_deterministic(measure: ModuleType) -> None:
    """Every fixture is explicitly seeded, so two runs must agree exactly.

    Without this, the check above would fail intermittently and get disabled.
    """
    assert measure.render(measure.SYNTHETIC) == measure.render(measure.SYNTHETIC)
