"""The measured tables in ``docs/`` must match what the code actually does.

Documentation that quotes numbers goes stale silently, and this project's docs
quote a lot of them — position bias, leakage suppression, agreement with
Prieto's package. Every one of those tables is generated by
``tools/measure_docs.py`` and injected between markers, so a change to an
estimator that moves a published number fails here instead of leaving the
prose quietly wrong.

Only the synthetic measurements are checked. The field ones read
``tutorial/data/events/`` and are slow; regenerate those by hand with
``python tools/measure_docs.py --write --field``.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parent.parent


def _load_measure_docs() -> ModuleType:
    """Import ``tools/measure_docs.py``, which is a script rather than a
    package member and so is not importable by name."""
    path = ROOT / "tools" / "measure_docs.py"
    spec = importlib.util.spec_from_file_location("measure_docs", path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["measure_docs"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def measure() -> ModuleType:
    return _load_measure_docs()


def test_every_marker_in_the_docs_has_a_measurement(measure: ModuleType) -> None:
    """A marker naming a measurement that no longer exists would be skipped
    silently, leaving its table frozen at whatever it last said."""
    known = set(measure.SYNTHETIC) | set(measure.FIELD)
    for path in measure.DOCS:
        if not path.exists():
            continue
        for match in measure.MARKER.finditer(path.read_text()):
            name = match.group("name")
            assert name in known, (
                f"{path.relative_to(ROOT)} refers to measurement {name!r}, which "
                f"is not defined in tools/measure_docs.py"
            )


def test_synthetic_tables_match_the_code(measure: ModuleType) -> None:
    """The check that actually bites: regenerate and compare."""
    rendered = measure.render(measure.SYNTHETIC)
    stale: list[str] = []
    for path in measure.DOCS:
        if path.exists():
            _, found = measure.apply_to(path, rendered)
            stale += found
    assert not stale, (
        "documented measurements no longer match the code: "
        + ", ".join(stale)
        + "\nrun: python tools/measure_docs.py --write"
    )


def test_measurements_are_deterministic(measure: ModuleType) -> None:
    """Every fixture is explicitly seeded, so two runs must agree exactly.

    Without this, the check above would fail intermittently and get disabled.
    """
    assert measure.render(measure.SYNTHETIC) == measure.render(measure.SYNTHETIC)


# ------------------------------------------------------- the notebook builders

#: Builders live beside the notebooks they write and are named after them, with
#: underscores where the notebook has hyphens. Anything ``_``-prefixed is shared
#: machinery rather than a builder.
BUILDERS = ROOT / "docs" / "notebooks" / "_builders"


def _builders() -> list[Path]:
    return sorted(p for p in BUILDERS.glob("*.py") if not p.name.startswith("_"))


def _notebook_for(builder: Path) -> Path:
    return BUILDERS.parent / f"{builder.stem.replace('_', '-')}.ipynb"


def test_every_builder_names_the_notebook_it_writes() -> None:
    """The convention, enforced rather than documented.

    A builder with no notebook is one nobody has run; a notebook with no
    builder is one nobody can rebuild. Either way the pair is the unit.
    """
    assert _builders(), "no notebook builders found"
    for builder in _builders():
        assert _notebook_for(builder).is_file(), (
            f"{builder.name} builds {_notebook_for(builder).name}, which does not exist"
        )
    built = {_notebook_for(b) for b in _builders()}
    for notebook in BUILDERS.parent.glob("*.ipynb"):
        assert notebook in built, (
            f"{notebook.name} has no builder. Add "
            f"{BUILDERS.name}/{notebook.stem.replace('-', '_')}.py, or move the "
            f"notebook out of docs/notebooks/ if it is maintained by hand."
        )


@pytest.mark.parametrize("builder", _builders(), ids=lambda p: p.stem)
def test_rebuilding_a_notebook_changes_nothing(builder: Path) -> None:
    """The builder is the source of truth, and can be shown to be.

    This had already stopped being true: the notebook had been through
    ``ruff format`` and had cell ids added, its builder had not, and the
    builder had been edited five times against the notebook's two. Rebuilding
    would have reverted the formatting of every code cell. The content still
    agreed cell for cell, which is the only reason it was recoverable.

    Running the builder is cheap — it writes strings, and imports nothing from
    the package — so there is no reason for this not to be checked on every
    run.
    """
    notebook = _notebook_for(builder)
    before = notebook.read_bytes()
    try:
        subprocess.run([sys.executable, str(builder)], check=True, capture_output=True)
        assert notebook.read_bytes() == before, (
            f"{notebook.name} is not what {builder.name} builds. Run it and "
            f"commit the result, or fix the builder — whichever is out of date."
        )
    finally:
        # Never leave the tree dirty, whichever way the assertion went.
        notebook.write_bytes(before)
